# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dmvnorm <- function(X, mean, Sigma) {
    .Call('_T4Gauss_cpp_dmvnorm', PACKAGE = 'T4Gauss', X, mean, Sigma)
}

rcpparma_hello_world <- function() {
    .Call('_T4Gauss_rcpparma_hello_world', PACKAGE = 'T4Gauss')
}

rcpparma_outerproduct <- function(x) {
    .Call('_T4Gauss_rcpparma_outerproduct', PACKAGE = 'T4Gauss', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_T4Gauss_rcpparma_innerproduct', PACKAGE = 'T4Gauss', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_T4Gauss_rcpparma_bothproducts', PACKAGE = 'T4Gauss', x)
}

