# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqrtm_covs <- function(covs3) {
    .Call('_T4Gauss_sqrtm_covs', PACKAGE = 'T4Gauss', covs3)
}

wass2_barycenter <- function(mean3, covs3, lambdas, maxiter, eps) {
    .Call('_T4Gauss_wass2_barycenter', PACKAGE = 'T4Gauss', mean3, covs3, lambdas, maxiter, eps)
}

wass2_dist <- function(mean3, covs3) {
    .Call('_T4Gauss_wass2_dist', PACKAGE = 'T4Gauss', mean3, covs3)
}

wass2_dist2 <- function(mean1, mean2, covs1, covs2) {
    .Call('_T4Gauss_wass2_dist2', PACKAGE = 'T4Gauss', mean1, mean2, covs1, covs2)
}

kl_dist <- function(mean3, covs3) {
    .Call('_T4Gauss_kl_dist', PACKAGE = 'T4Gauss', mean3, covs3)
}

kl_dist2 <- function(mean1, covs1, mean2, covs2) {
    .Call('_T4Gauss_kl_dist2', PACKAGE = 'T4Gauss', mean1, covs1, mean2, covs2)
}

skl_dist2 <- function(mean1, covs1, mean2, covs2) {
    .Call('_T4Gauss_skl_dist2', PACKAGE = 'T4Gauss', mean1, covs1, mean2, covs2)
}

cs_dist <- function(mean3, covs3) {
    .Call('_T4Gauss_cs_dist', PACKAGE = 'T4Gauss', mean3, covs3)
}

cs_dist2 <- function(mean1, covs1, mean2, covs2) {
    .Call('_T4Gauss_cs_dist2', PACKAGE = 'T4Gauss', mean1, covs1, mean2, covs2)
}

bh_dist <- function(mean3, covs3) {
    .Call('_T4Gauss_bh_dist', PACKAGE = 'T4Gauss', mean3, covs3)
}

bh_dist2 <- function(mean1, covs1, mean2, covs2) {
    .Call('_T4Gauss_bh_dist2', PACKAGE = 'T4Gauss', mean1, covs1, mean2, covs2)
}

cpp_dmvnorm <- function(X, mean, Sigma) {
    .Call('_T4Gauss_cpp_dmvnorm', PACKAGE = 'T4Gauss', X, mean, Sigma)
}

wass2covs_mu <- function(means, lambdas) {
    .Call('_T4Gauss_wass2covs_mu', PACKAGE = 'T4Gauss', means, lambdas)
}

wass2covs_fmean <- function(covs, lambdas, maxiter, eps) {
    .Call('_T4Gauss_wass2covs_fmean', PACKAGE = 'T4Gauss', covs, lambdas, maxiter, eps)
}

wass2covs_fmean_openmp <- function(covs, lambdas, maxiter, eps, nCores) {
    .Call('_T4Gauss_wass2covs_fmean_openmp', PACKAGE = 'T4Gauss', covs, lambdas, maxiter, eps, nCores)
}

wass2covs_fmedian <- function(covs, lambdas, maxiter, eps) {
    .Call('_T4Gauss_wass2covs_fmedian', PACKAGE = 'T4Gauss', covs, lambdas, maxiter, eps)
}

wass2covs_fmedian_openmp <- function(covs, lambdas, maxiter, eps, nCores) {
    .Call('_T4Gauss_wass2covs_fmedian_openmp', PACKAGE = 'T4Gauss', covs, lambdas, maxiter, eps, nCores)
}

arma_gmm_full <- function(X, k, maxiter) {
    .Call('_T4Gauss_arma_gmm_full', PACKAGE = 'T4Gauss', X, k, maxiter)
}

arma_gmm_diag <- function(X, k, maxiter) {
    .Call('_T4Gauss_arma_gmm_diag', PACKAGE = 'T4Gauss', X, k, maxiter)
}

wass2_interp <- function(m0, m1, sig0, sig1, t) {
    .Call('_T4Gauss_wass2_interp', PACKAGE = 'T4Gauss', m0, m1, sig0, sig1, t)
}

